name: Build Pacman Packages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup environment
      run: |
        pacman -Syu --noconfirm base-devel pacman-contrib git
        useradd -m builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        
    - name: Build package
      run: |
        cd packages/test-repo
    	sudo -u builder makepkg -s --noconfirm
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quasar-packages
        path: packages/test-package/*.pkg.tar.zst
