name: Build Pacman Packages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup environment
      run: |
        pacman -Syu --noconfirm base-devel pacman-contrib git
        useradd -m builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
    - name: Debug directory structure
      run: |
        pwd
        ls -la
        ls -la packages/
    - name: Build package
      run: |
        chmod -R 777 packages/openrc
        cd packages/openrc
        sudo -u builder makepkg -s --noconfirm
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quasar-openrc
        path: packages/openrc/*.pkg.tar.zst
